# Generated by Django 2.2.6 on 2019-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company/default.jpeg', upload_to='company/profile_pics'),
        ),
    ]
