# Generated by Django 2.2.6 on 2019-10-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20191020_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email01',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
