# Generated by Django 2.2.6 on 2019-10-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191018_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
