# Generated by Django 2.2.6 on 2019-10-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_email02'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='webPage',
            field=models.CharField(default='', max_length=250),
        ),
    ]
